name: heritage
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  go_router: ^14.2.7
  flutter_riverpod: ^2.5.1
  fpdart: ^1.1.0
  http: ^1.2.2  
  package_info_plus: ^8.0.2
  sentry_flutter: ^8.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
