name: heritage
description: "A new Flutter project."
publish_to: 'none'

version: 0.8.6+7

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  collection: ^1.18.0
  cross_file: ^0.3.4+2
  cupertino_icons: ^1.0.8  
  file_picker: ^8.1.2
  flutter_riverpod: ^2.5.1 
  flutter_svg: ^2.0.10+1
  fpdart: ^1.1.0  
  freezed_annotation: ^2.4.4  
  go_router: ^14.2.7
  http: ^1.2.2 
  image: ^4.2.0  
  intl: ^0.19.0
  json_annotation: ^4.9.0
  lottie: ^3.1.2
  package_info_plus: ^8.0.2
  path_drawing: ^1.0.1
  sentry_flutter: ^8.9.0
  share_plus: ^10.0.2
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  vector_math: ^2.1.4
  web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/badge.svg
    - assets/images/binoculars.png
    - assets/images/connection_child.svg
    - assets/images/connection_parent.svg
    - assets/images/connection_sibling.svg
    - assets/images/connection_spouse.svg
    - assets/images/logo_text.png
    - assets/images/logo.json
    - assets/images/perspective_portal.png
    - assets/images/tagline.png
    - assets/images/tree_background.png

  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Ultralight.otf
          weight: 100
        - asset: assets/fonts/SF-Pro-Display-Thin.otf
          weight: 200
        - asset: assets/fonts/SF-Pro-Display-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Display-Heavy.otf
          weight: 800
        - asset: assets/fonts/SF-Pro-Display-Black.otf
          weight: 900
